<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="Version.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Numos.CoreSim</RootNamespace>
        <PackageId>Numos.CoreSim</PackageId>
        <Title>Numos CoreSim</Title>
        <Description>Engine-agnostic, pseudo-realistic, voxel-based atmospherics simulation kernel.</Description>
        <PackageTags>simulation;atmospherics;voxel;nativeaot</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GenerateNumosBuildInfo>true</GenerateNumosBuildInfo>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Numos.Maths\Numos.Maths.csproj"/>
    </ItemGroup>

</Project>
