using Numos.CoreSim.Replay;

namespace Numos.CoreSim.Tests.Replay;

/// <summary>
///     Exercises the checkpoint fields whose capture/restore/hash code is generated by
///     <c>Numos.Replay.CheckpointGen</c> (<see cref="ChunkCheckpointFieldAttribute" />-tagged chunk arrays,
///     <see cref="ConfigCheckpointFieldAttribute" />-tagged <see cref="AtmosConfigSnapshot" /> scalars, and
///     <see cref="GasCheckpointFieldAttribute" />-tagged <see cref="GasProperties" /> fields), directly
///     against <c>AtmosChunkCheckpoint</c>/<c>AtmosStateHasher</c> internals rather than only through the public
///     replay API in <c>Numos.API.Tests</c>.
/// </summary>
[TestFixture]
public sealed class CheckpointFieldGenerationParityTests
{
    [Test]
    public void ChunkCheckpoint_CapturesTaggedArraysFromLiveChunk()
    {
        var chunk = new AtmosChunk(2, 1, 1);
        chunk.VoxelRoomMap[0] = 5;
        chunk.VoxelRoomMap[1] = 7;
        chunk.Temperature[0] = 301f;
        chunk.Temperature[1] = 302f;
        chunk.TotalPressure[0] = 100f;
        chunk.TotalPressure[1] = 0f;
        chunk.TotalHeatCapacity[0] = 12f;
        chunk.TotalHeatCapacity[1] = 13f;

        var checkpoint = new AtmosChunkCheckpoint(chunk);

        Assert.Multiple(() =>
        {
            Assert.That(checkpoint.Classifications, Is.EqualTo(new[] { 5, 7 }));
            Assert.That(checkpoint.Temperatures, Is.EqualTo(new[] { 301f, 302f }));
            Assert.That(checkpoint.Pressures, Is.EqualTo(new[] { 100f, 0f }));
            Assert.That(checkpoint.HeatCapacities, Is.EqualTo(new[] { 12f, 13f }));
        });
    }

    [Test]
    public void ChunkCheckpoint_MaterializeRoundTripsTaggedArraysAndDerivedVacuumFlag()
    {
        var chunk = new AtmosChunk(2, 1, 1);
        chunk.VoxelRoomMap[0] = 5;
        chunk.VoxelRoomMap[1] = 7;
        chunk.Temperature[0] = 301f;
        chunk.Temperature[1] = 302f;
        chunk.TotalPressure[0] = 100f;
        chunk.TotalPressure[1] = 0f;
        chunk.TotalHeatCapacity[0] = 12f;
        chunk.TotalHeatCapacity[1] = 13f;
        var checkpoint = new AtmosChunkCheckpoint(chunk);

        var restored = checkpoint.Materialize();

        Assert.Multiple(() =>
        {
            Assert.That(restored.VoxelRoomMap[0], Is.EqualTo(5));
            Assert.That(restored.VoxelRoomMap[1], Is.EqualTo(7));
            Assert.That(restored.Temperature[0], Is.EqualTo(301f));
            Assert.That(restored.Temperature[1], Is.EqualTo(302f));
            Assert.That(restored.TotalPressure[0], Is.EqualTo(100f));
            Assert.That(restored.TotalPressure[1], Is.EqualTo(0f));
            Assert.That(restored.TotalHeatCapacity[0], Is.EqualTo(12f));
            Assert.That(restored.TotalHeatCapacity[1], Is.EqualTo(13f));

            // IsVacuum is derived from Pressures rather than captured directly, so this specifically checks the
            // hand-written line next to the generated per-voxel restore still runs against the restored values.
            Assert.That(restored.IsVacuum[0], Is.False);
            Assert.That(restored.IsVacuum[1], Is.True);
        });
    }

    [Test]
    public void ChunkFieldsHash_IsStableAcrossRepeatedComputation()
    {
        var chunk = new AtmosChunk(2, 1, 1);
        chunk.VoxelRoomMap[0] = 5;
        chunk.Temperature[0] = 301f;
        chunk.TotalPressure[0] = 100f;
        chunk.TotalHeatCapacity[0] = 12f;
        var checkpoint = new AtmosChunkCheckpoint(chunk);

        var first = new AtmosStateHasher();
        GeneratedCheckpointFields.AppendChunkFields(ref first, checkpoint);

        var second = new AtmosStateHasher();
        GeneratedCheckpointFields.AppendChunkFields(ref second, checkpoint);

        Assert.That(first.Value, Is.EqualTo(second.Value));
    }

    [Test]
    public void ConfigHash_ChangesWhenATaggedScalarChanges()
    {
        var baseline = new AtmosConfig { ThermalConductance = 0.1f }.CreateSnapshot();
        var changed = new AtmosConfig { ThermalConductance = 0.2f }.CreateSnapshot();

        var baselineHash = new AtmosStateHasher();
        baseline.AppendHash(ref baselineHash);
        var changedHash = new AtmosStateHasher();
        changed.AppendHash(ref changedHash);

        Assert.That(baselineHash.Value, Is.Not.EqualTo(changedHash.Value));
    }

    [Test]
    public void GasHash_ChangesWhenATaggedFieldChanges()
    {
        var baselineHash = new AtmosStateHasher();
        baselineHash.Add(new GasProperties { Name = "Air", DiffusionCoefficient = 0.02f });

        var changedHash = new AtmosStateHasher();
        changedHash.Add(new GasProperties { Name = "Air", DiffusionCoefficient = 0.05f });

        Assert.That(baselineHash.Value, Is.Not.EqualTo(changedHash.Value));
    }
}
