<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Numos</RootNamespace>
        <PackageId>Numos.API</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Numos.CoreSim\Numos.CoreSim.csproj"/>
    </ItemGroup>

</Project>
