<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>WinExe</OutputType>
        <RootNamespace>Numos.Viewer</RootNamespace>
        <AssemblyName>Numos.Viewer</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Numos.API\Numos.API.csproj"/>
        <ProjectReference Include="..\Numos.SimDrawer\Numos.SimDrawer.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Raylib-cs" Version="7.0.2"/>
        <PackageReference Include="rlImgui-cs" Version="3.2.0"/>
    </ItemGroup>

</Project>
