using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Numos.Replay.SourceGen;

/// <summary>
///     Generates the paired read/write wire codec for Numos replay operations from <c>[WireOperation]</c>-annotated
///     descriptors, replacing the hand-written per-opcode switch statements in the replay serializers.
/// </summary>
/// <remarks>
///     Covers both the simulation-level <c>AtmosOperation</c> family and the world-level <c>AtmosWorldOperation</c>
///     family. Every registration is a <c>[WireOperation(typeof(Op), Code)]</c> attribute stacked directly on the
///     class that should receive that family's generated codec (<c>NumosReplaySerializer</c> or
///     <c>NumosWorldReplaySerializer</c>) -- there is nowhere else to look, which is also what lets this generator
///     use the fully-incremental <c>ForAttributeWithMetadataName</c> API instead of re-scanning the whole
///     compilation on every edit. Most operations' fields map onto a small, fixed set of recognized wire
///     primitives (see <see cref="TryGetWireKind" />), including one nested-operation kind that lets a world
///     operation embed a whole simulation operation (its opcode plus a delegated call into the sim family's own
///     codec); their codec bodies are fully generated from the record's primary-constructor shape. Operations with
///     bespoke serialization (a nested config snapshot, a variable-length list) set <c>Custom = true</c> instead --
///     the generator validates their hand-written <c>Write{Name}</c>/<c>Read{Name}</c> methods' signatures and
///     plugs calls to them into the same generated dispatch table, rather than guessing at the bespoke shape
///     itself. Each family's codec is emitted into whichever namespace/class its own registrations are actually
///     stacked on (not a hardcoded name), so misplacing a registration fails where it was placed instead of
///     silently landing in the other family's file.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class ReplayCodecGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
                                            // <auto-generated/>
                                            #nullable enable

                                            namespace Numos.Replay.SourceGen
                                            {
                                                /// <summary>
                                                ///     Registers an <c>AtmosOperation</c> or <c>AtmosWorldOperation</c> record's wire-format codec for
                                                ///     source generation, keyed by its stable opcode.
                                                /// </summary>
                                                /// <remarks>
                                                ///     Stack one instance per opcode directly on the class that should receive the generated codec (e.g.
                                                ///     <c>NumosReplaySerializer</c>) -- <c>AllowMultiple</c> is required for that one-line-per-opcode usage.
                                                /// </remarks>
                                                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
                                                internal sealed class WireOperationAttribute : global::System.Attribute
                                                {
                                                    /// <param name="operationType">The annotated operation record.</param>
                                                    /// <param name="code">
                                                    ///     The record's stable <c>AtmosOperationCode</c> or <c>AtmosWorldOperationCode</c> discriminator.
                                                    /// </param>
                                                    public WireOperationAttribute(global::System.Type operationType, object code)
                                                    {
                                                        OperationType = operationType;
                                                        Code = code;
                                                    }

                                                    /// <summary>Gets the annotated operation record.</summary>
                                                    public global::System.Type OperationType { get; }

                                                    /// <summary>Gets the record's stable opcode discriminator.</summary>
                                                    public object Code { get; }

                                                    /// <summary>
                                                    ///     Gets or sets whether the codec body is hand-written and only registered into the generated
                                                    ///     dispatch table, rather than generated from the record's primary-constructor shape.
                                                    /// </summary>
                                                    public bool Custom { get; set; }
                                                }
                                            }
                                            """;

    private const string WireOperationAttributeMetadataName = "Numos.Replay.SourceGen.WireOperationAttribute";
    private const string SimOperationBaseMetadataName = "Numos.CoreSim.Replay.AtmosOperation";
    private const string SimOperationCodeMetadataName = "Numos.CoreSim.Replay.AtmosOperationCode";
    private const string WorldOperationBaseMetadataName = "Numos.API.AtmosWorldOperation";
    private const string WorldOperationCodeMetadataName = "Numos.API.AtmosWorldOperationCode";
    private const string SimReadOptionsMetadataName = "Numos.Serialization.NumosReplayReadOptions";
    private const string BinaryWriterMetadataName = "System.IO.BinaryWriter";
    private const string BinaryReaderMetadataName = "System.IO.BinaryReader";

    private static readonly SymbolDisplayFormat FullyQualified = SymbolDisplayFormat.FullyQualifiedFormat;

    private static readonly DiagnosticDescriptor UnsupportedFieldType = new(
        "NUMOSREPLAYGEN001",
        "Unsupported wire field type",
        "Operation '{0}' has a field '{1}' of type '{2}', which this generator does not know how to serialize; " +
        "mark the registration Custom and hand-write its codec, or extend the generator's wire-kind table",
        "Numos.Replay.SourceGen",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor AmbiguousConstructor = new(
        "NUMOSREPLAYGEN002",
        "Operation record has no single primary constructor",
        "Operation '{0}' must declare exactly one non-copy constructor for its wire fields",
        "Numos.Replay.SourceGen",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor MissingCustomMethod = new(
        "NUMOSREPLAYGEN007",
        "Missing or mismatched custom codec method",
        "Operation '{0}' has no accessible '{1}' member matching the expected signature '{2}'",
        "Numos.Replay.SourceGen",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor DuplicateCode = new(
        "NUMOSREPLAYGEN004",
        "Duplicate wire operation code",
        "More than one [WireOperation] registration uses code '{0}'",
        "Numos.Replay.SourceGen",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor UnrecognizedFamily = new(
        "NUMOSREPLAYGEN005",
        "Unrecognized wire operation family",
        "Operation '{0}' does not derive from a known operation base type, or its code is not a recognized " +
        "opcode enum",
        "Numos.Replay.SourceGen",
        DiagnosticSeverity.Error,
        true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(
            static production => production.AddSource("Numos.Replay.WireOperationAttribute.g.cs", AttributeSource));

        IncrementalValuesProvider<GeneratorAttributeSyntaxContext> registrationHosts = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                WireOperationAttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (syntaxContext, _) => syntaxContext);

        IncrementalValueProvider<CollectedRegistrations> collected = registrationHosts.Collect()
            .Select(static (hosts, cancellationToken) => Collect(hosts, cancellationToken));

        context.RegisterSourceOutput(collected, static (production, result) =>
        {
            foreach (var diagnostic in result.Diagnostics)
                production.ReportDiagnostic(diagnostic);

            if (result.SimOperations.Count > 0 && result.SimHostType is { } simHost)
            {
                production.AddSource(
                    "Numos.Replay.SimulationOperationCodec.g.cs",
                    GenerateCodec(simHost, SimOperationBaseMetadataName, SimOperationCodeMetadataName, result.SimOperations));
            }

            if (result.WorldOperations.Count > 0 && result.WorldHostType is { } worldHost)
            {
                production.AddSource(
                    "Numos.Replay.WorldOperationCodec.g.cs",
                    GenerateCodec(worldHost, WorldOperationBaseMetadataName, WorldOperationCodeMetadataName, result.WorldOperations));
            }
        });
    }

    private static CollectedRegistrations Collect(
        ImmutableArray<GeneratorAttributeSyntaxContext> hosts, CancellationToken cancellationToken)
    {
        var diagnostics = new List<Diagnostic>();
        var simOperations = new List<OperationPlan>();
        var worldOperations = new List<OperationPlan>();
        var state = new CollectionState(diagnostics, simOperations, worldOperations);
        if (hosts.IsEmpty)
            return state.ToResult();

        // All hosts are ClassDeclarationSyntax nodes from the same generator run, so they share one compilation --
        // resolving well-known types from hosts[0] is safe regardless of how many distinct host classes appear.
        Compilation compilation = hosts[0].SemanticModel.Compilation;
        state.SimBase = compilation.GetTypeByMetadataName(SimOperationBaseMetadataName);
        state.SimCodeEnum = compilation.GetTypeByMetadataName(SimOperationCodeMetadataName);
        state.WorldBase = compilation.GetTypeByMetadataName(WorldOperationBaseMetadataName);
        state.WorldCodeEnum = compilation.GetTypeByMetadataName(WorldOperationCodeMetadataName);
        state.BinaryWriterType = compilation.GetTypeByMetadataName(BinaryWriterMetadataName);
        state.BinaryReaderType = compilation.GetTypeByMetadataName(BinaryReaderMetadataName);
        state.ReadOptionsType = compilation.GetTypeByMetadataName(SimReadOptionsMetadataName);

        foreach (var host in hosts)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (host.TargetSymbol is not INamedTypeSymbol hostType)
                continue;

            foreach (var attribute in host.Attributes)
            {
                cancellationToken.ThrowIfCancellationRequested();
                ProcessRegistration(attribute, hostType, state);
            }
        }

        return state.ToResult();
    }

    private static void ProcessRegistration(AttributeData attribute, INamedTypeSymbol hostType, CollectionState state)
    {
        Location location = attribute.ApplicationSyntaxReference?.GetSyntax().GetLocation() ?? Location.None;
        if (attribute.ConstructorArguments.Length != 2 || attribute.ConstructorArguments[0].Value is not INamedTypeSymbol operationType)
            return;

        string operationDisplayName = operationType.ToDisplayString();
        TypedConstant codeConstant = attribute.ConstructorArguments[1];
        if (!TryResolveFamily(operationType, codeConstant, state, location, operationDisplayName, out bool isWorld, out var codeEnum))
            return;

        List<OperationPlan> operations = isWorld ? state.WorldOperations : state.SimOperations;
        if (isWorld)
            state.WorldHostType ??= hostType;
        else
            state.SimHostType ??= hostType;

        if (!TryReserveCode(codeEnum, codeConstant, state.SeenCodes, location, state.Diagnostics))
            return;

        if (IsCustom(attribute))
        {
            ProcessCustomRegistration(
                operationType, operationDisplayName, codeConstant, hostType, codeEnum, state.BinaryWriterType, state.BinaryReaderType,
                state.ReadOptionsType, location, operations, state.Diagnostics);
            return;
        }

        IMethodSymbol? constructor = FindPrimaryConstructor(operationType);
        if (constructor is null)
        {
            state.Diagnostics.Add(Diagnostic.Create(AmbiguousConstructor, location, operationDisplayName));
            return;
        }

        var fields = new List<FieldPlan>();
        bool ok = true;
        foreach (var parameter in constructor.Parameters)
        {
            if (!TryGetWireKind(parameter.Type, out string writeTemplate, out string readExpression))
            {
                state.Diagnostics.Add(Diagnostic.Create(
                    UnsupportedFieldType, location, operationDisplayName, parameter.Name, parameter.Type.ToDisplayString()));
                ok = false;
                continue;
            }

            fields.Add(new FieldPlan(parameter.Name, writeTemplate, readExpression));
        }

        if (!ok)
            return;

        string caseLabel = ResolveEnumMemberExpression(codeEnum, codeConstant);
        operations.Add(OperationPlan.Mechanical(operationType.ToDisplayString(FullyQualified), caseLabel, fields));
    }

    private static void ProcessCustomRegistration(
        INamedTypeSymbol operationType,
        string operationDisplayName,
        TypedConstant codeConstant,
        INamedTypeSymbol hostType,
        INamedTypeSymbol codeEnum,
        INamedTypeSymbol? binaryWriterType,
        INamedTypeSymbol? binaryReaderType,
        INamedTypeSymbol? readOptionsType,
        Location location,
        List<OperationPlan> operations,
        List<Diagnostic> diagnostics)
    {
        string writeMethodName = "Write" + operationType.Name;
        string readMethodName = "Read" + operationType.Name;

        var writeMethod = FindMatchingMethod(hostType, writeMethodName, expectedReturn: null, [binaryWriterType, operationType]);
        if (writeMethod is null)
        {
            string expected = $"static void {writeMethodName}(global::System.IO.BinaryWriter writer, {operationDisplayName} operation)";
            diagnostics.Add(Diagnostic.Create(MissingCustomMethod, location, operationDisplayName, writeMethodName, expected));
            return;
        }

        var readMethod = FindMatchingMethod(hostType, readMethodName, expectedReturn: operationType, [binaryReaderType, readOptionsType]);
        if (readMethod is null)
        {
            string optionsName = readOptionsType?.ToDisplayString(FullyQualified) ?? SimReadOptionsMetadataName;
            string expected = $"static {operationDisplayName} {readMethodName}(global::System.IO.BinaryReader reader, {optionsName} options)";
            diagnostics.Add(Diagnostic.Create(MissingCustomMethod, location, operationDisplayName, readMethodName, expected));
            return;
        }

        string caseLabel = ResolveEnumMemberExpression(codeEnum, codeConstant);
        operations.Add(OperationPlan.Custom(operationType.ToDisplayString(FullyQualified), caseLabel, writeMethodName, readMethodName));
    }

    private static bool IsCustom(AttributeData attribute)
    {
        return attribute.NamedArguments
            .Where(static pair => pair.Key == "Custom")
            .Select(static pair => pair.Value.Value as bool?)
            .FirstOrDefault() ?? false;
    }

    private static bool TryResolveFamily(
        INamedTypeSymbol operationType,
        TypedConstant codeConstant,
        CollectionState state,
        Location location,
        string operationDisplayName,
        out bool isWorld,
        out INamedTypeSymbol codeEnum)
    {
        if (state.SimBase is { } simBase && state.SimCodeEnum is { } simCodeEnum &&
            InheritsFrom(operationType, simBase) && SymbolEqualityComparer.Default.Equals(codeConstant.Type, simCodeEnum))
        {
            isWorld = false;
            codeEnum = simCodeEnum;
            return true;
        }

        if (state.WorldBase is { } worldBase && state.WorldCodeEnum is { } worldCodeEnum &&
            InheritsFrom(operationType, worldBase) && SymbolEqualityComparer.Default.Equals(codeConstant.Type, worldCodeEnum))
        {
            isWorld = true;
            codeEnum = worldCodeEnum;
            return true;
        }

        state.Diagnostics.Add(Diagnostic.Create(UnrecognizedFamily, location, operationDisplayName));
        isWorld = false;
        codeEnum = null!;
        return false;
    }

    private static bool TryReserveCode(
        INamedTypeSymbol codeEnum, TypedConstant codeConstant, HashSet<string> seenCodes, Location location, List<Diagnostic> diagnostics)
    {
        // Prefixed with the enum's own name: AtmosOperationCode and (once Phase 4 adds the world family) an
        // AtmosWorldOperationCode member can share the same underlying numeric value without colliding here.
        string codeKey = codeEnum.ToDisplayString(FullyQualified) + ":" +
                          (Convert.ToString(codeConstant.Value, CultureInfo.InvariantCulture) ?? "null");
        if (seenCodes.Add(codeKey))
            return true;

        diagnostics.Add(Diagnostic.Create(DuplicateCode, location, codeKey));
        return false;
    }

    private static IMethodSymbol? FindMatchingMethod(
        INamedTypeSymbol hostType, string name, ITypeSymbol? expectedReturn, ITypeSymbol?[] expectedParameters)
    {
        foreach (var candidate in hostType.GetMembers(name).OfType<IMethodSymbol>())
        {
            // The generated call site is unqualified (e.g. "WriteFoo(writer, op);") from inside a static method,
            // so an instance method with an otherwise-matching signature would pass every other check here and
            // then fail to compile with a confusing CS0120 pointing at generated source instead of the real cause.
            if (!candidate.IsStatic)
                continue;

            if (candidate.Parameters.Length != expectedParameters.Length)
                continue;

            bool parametersMatch = true;
            for (int index = 0; index < expectedParameters.Length; index++)
            {
                if (expectedParameters[index] is null ||
                    !SymbolEqualityComparer.Default.Equals(candidate.Parameters[index].Type, expectedParameters[index]))
                {
                    parametersMatch = false;
                    break;
                }
            }

            if (!parametersMatch)
                continue;

            bool returnMatches = expectedReturn is null
                ? candidate.ReturnsVoid
                : SymbolEqualityComparer.Default.Equals(candidate.ReturnType, expectedReturn);

            if (returnMatches)
                return candidate;
        }

        return null;
    }

    private static bool InheritsFrom(ITypeSymbol type, INamedTypeSymbol baseType)
    {
        for (var current = type.BaseType; current != null; current = current.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
                return true;
        }

        return false;
    }

    private static IMethodSymbol? FindPrimaryConstructor(INamedTypeSymbol type)
    {
        var candidates = type.InstanceConstructors
            .Where(ctor => !(ctor.Parameters.Length == 1 && SymbolEqualityComparer.Default.Equals(ctor.Parameters[0].Type, type)))
            .ToList();

        return candidates.Count == 1 ? candidates[0] : null;
    }

    private static bool TryGetWireKind(ITypeSymbol type, out string writeTemplate, out string readExpression)
    {
        switch (type.SpecialType)
        {
            case SpecialType.System_UInt16:
                writeTemplate = "writer.Write({0});";
                readExpression = "reader.ReadUInt16()";
                return true;
            case SpecialType.System_Int32:
                writeTemplate = "writer.Write({0});";
                readExpression = "reader.ReadInt32()";
                return true;
            case SpecialType.System_Single:
                writeTemplate = "writer.Write({0});";
                readExpression = "reader.ReadSingle()";
                return true;
            case SpecialType.System_Boolean:
                writeTemplate = "writer.Write({0});";
                readExpression = "reader.ReadBoolean()";
                return true;
            case SpecialType.System_String:
                // Fully qualified for the same reason as Int3 below: this helper lives on NumosReplaySerializer,
                // and the world family's codec is emitted as a partial member of a different class.
                writeTemplate = "global::Numos.Serialization.NumosReplaySerializer.WriteString(writer, {0});";
                readExpression = "global::Numos.Serialization.NumosReplaySerializer.ReadString(reader, options)";
                return true;
        }

        switch (type.ToDisplayString(FullyQualified))
        {
            case "global::Numos.Maths.Int3":
                // Fully qualified rather than an unqualified "WriteInt3(...)" call: this helper lives on
                // NumosReplaySerializer, but a codec generated for the world family is emitted as a partial member
                // of a *different* class (NumosWorldReplaySerializer), which has no unqualified access to it.
                writeTemplate = "global::Numos.Serialization.NumosReplaySerializer.WriteInt3(writer, {0});";
                readExpression = "global::Numos.Serialization.NumosReplaySerializer.ReadInt3(reader)";
                return true;
            case "global::Numos.CoreSim.Datatypes.Primitives.VoxelClassification":
                writeTemplate = "writer.Write({0}.RoomId);";
                readExpression = "new global::Numos.CoreSim.Datatypes.Primitives.VoxelClassification(reader.ReadInt32())";
                return true;
            case "global::Numos.API.AtmosSimulationId":
                // WriteSimulationId/ReadSimulationId are private helpers already declared directly on
                // NumosWorldReplaySerializer (shared with its hand-written checkpoint codec) -- only world
                // operations ever have a field of this type, so calling them unqualified is safe.
                writeTemplate = "WriteSimulationId(writer, {0});";
                readExpression = "ReadSimulationId(reader)";
                return true;
            case "global::Numos.API.ExplicitLinkSetHandle":
                writeTemplate = "WriteHandle(writer, {0});";
                readExpression = "ReadHandle(reader)";
                return true;
            case "global::Numos.CoreSim.Replay.AtmosOperation":
                // A nested simulation operation: write its own opcode, then delegate to the sim family's codec for
                // the payload. On read, argument evaluation order is guaranteed left-to-right in C#, so
                // "reader.ReadUInt16()" consumes the opcode before ReadOperation reads the payload that follows it
                // on the wire -- do not reorder these arguments.
                writeTemplate = "writer.Write((ushort){0}.Code);\n" +
                                "                    global::Numos.Serialization.NumosReplaySerializer.WriteOperation(writer, {0});";
                readExpression = "global::Numos.Serialization.NumosReplaySerializer.ReadOperation(reader, reader.ReadUInt16(), options)";
                return true;
        }

        writeTemplate = "";
        readExpression = "";
        return false;
    }

    private static string ResolveEnumMemberExpression(INamedTypeSymbol enumType, TypedConstant value)
    {
        string enumFqn = enumType.ToDisplayString(FullyQualified);
        foreach (var member in enumType.GetMembers().OfType<IFieldSymbol>())
        {
            if (member.HasConstantValue && Equals(member.ConstantValue, value.Value))
                return $"{enumFqn}.{member.Name}";
        }

        return $"({enumFqn}){Convert.ToString(value.Value, CultureInfo.InvariantCulture)}";
    }

    private static string GenerateCodec(
        INamedTypeSymbol hostType, string baseTypeMetadataName, string codeEnumMetadataName, List<OperationPlan> operations)
    {
        string hostNamespace = hostType.ContainingNamespace.ToDisplayString();
        string hostName = hostType.Name;
        string baseTypeFqn = "global::" + baseTypeMetadataName;
        string codeEnumFqn = "global::" + codeEnumMetadataName;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").AppendLine(hostNamespace);
        builder.AppendLine("{");
        builder.Append("    public static partial class ").AppendLine(hostName);
        builder.AppendLine("    {");
        builder.Append(
            "        private static bool TryWriteGeneratedOperation(global::System.IO.BinaryWriter writer, ").Append(baseTypeFqn).AppendLine(" operation)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (operation)");
        builder.AppendLine("            {");
        foreach (var operation in operations)
        {
            builder.Append("                case ").Append(operation.FullyQualifiedTypeName).AppendLine(" op:");
            if (operation.Fields != null)
            {
                foreach (var field in operation.Fields)
                    builder.Append("                    ").AppendLine(string.Format(CultureInfo.InvariantCulture, field.WriteTemplate, "op." + field.ParameterName));
            }
            else
            {
                builder.Append("                    ").Append(operation.CustomWriteMethod).AppendLine("(writer, op);");
            }

            builder.AppendLine("                    return true;");
        }

        builder.AppendLine("                default:");
        builder.AppendLine("                    return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.Append(
            "        private static bool TryReadGeneratedOperation(global::System.IO.BinaryReader reader, ushort code, " +
            "global::Numos.Serialization.NumosReplayReadOptions options, out ").Append(baseTypeFqn).AppendLine("? operation)");
        builder.AppendLine("        {");
        builder.Append("            switch ((").Append(codeEnumFqn).AppendLine(")code)");
        builder.AppendLine("            {");
        foreach (var operation in operations)
        {
            builder.Append("                case ").Append(operation.CaseLabel).AppendLine(":");
            if (operation.Fields != null)
            {
                string args = string.Join(", ", operation.Fields.Select(static field => field.ReadExpression));
                builder.Append("                    operation = new ").Append(operation.FullyQualifiedTypeName).Append('(').Append(args).AppendLine(");");
            }
            else
            {
                builder.Append("                    operation = ").Append(operation.CustomReadMethod).AppendLine("(reader, options);");
            }

            builder.AppendLine("                    return true;");
        }

        builder.AppendLine("                default:");
        builder.AppendLine("                    operation = null;");
        builder.AppendLine("                    return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private sealed class CollectedRegistrations
    {
        public CollectedRegistrations(
            List<Diagnostic> diagnostics,
            List<OperationPlan> simOperations,
            List<OperationPlan> worldOperations,
            INamedTypeSymbol? simHostType,
            INamedTypeSymbol? worldHostType)
        {
            Diagnostics = diagnostics;
            SimOperations = simOperations;
            WorldOperations = worldOperations;
            SimHostType = simHostType;
            WorldHostType = worldHostType;
        }

        public List<Diagnostic> Diagnostics { get; }

        public List<OperationPlan> SimOperations { get; }

        public List<OperationPlan> WorldOperations { get; }

        public INamedTypeSymbol? SimHostType { get; }

        public INamedTypeSymbol? WorldHostType { get; }
    }

    /// <summary>Mutable scratch state threaded through one <see cref="Collect" /> run.</summary>
    private sealed class CollectionState
    {
        public CollectionState(List<Diagnostic> diagnostics, List<OperationPlan> simOperations, List<OperationPlan> worldOperations)
        {
            Diagnostics = diagnostics;
            SimOperations = simOperations;
            WorldOperations = worldOperations;
        }

        public List<Diagnostic> Diagnostics { get; }

        public List<OperationPlan> SimOperations { get; }

        public List<OperationPlan> WorldOperations { get; }

        public HashSet<string> SeenCodes { get; } = new(StringComparer.Ordinal);

        public INamedTypeSymbol? SimBase { get; set; }

        public INamedTypeSymbol? SimCodeEnum { get; set; }

        public INamedTypeSymbol? WorldBase { get; set; }

        public INamedTypeSymbol? WorldCodeEnum { get; set; }

        public INamedTypeSymbol? BinaryWriterType { get; set; }

        public INamedTypeSymbol? BinaryReaderType { get; set; }

        public INamedTypeSymbol? ReadOptionsType { get; set; }

        /// <summary>The class the first registration of each family was found on; used to emit that family's codec
        /// into the same namespace/class rather than a hardcoded name, so a misplaced registration fails where it
        /// was placed instead of silently landing in the other family's file.</summary>
        public INamedTypeSymbol? SimHostType { get; set; }

        public INamedTypeSymbol? WorldHostType { get; set; }

        public CollectedRegistrations ToResult()
        {
            return new CollectedRegistrations(Diagnostics, SimOperations, WorldOperations, SimHostType, WorldHostType);
        }
    }

    private sealed class OperationPlan
    {
        private OperationPlan(
            string fullyQualifiedTypeName, string caseLabel, List<FieldPlan>? fields, string? customWriteMethod, string? customReadMethod)
        {
            FullyQualifiedTypeName = fullyQualifiedTypeName;
            CaseLabel = caseLabel;
            Fields = fields;
            CustomWriteMethod = customWriteMethod;
            CustomReadMethod = customReadMethod;
        }

        public string FullyQualifiedTypeName { get; }

        public string CaseLabel { get; }

        /// <summary>Field-order wire schema for a generated codec body; <see langword="null" /> for a Custom operation.</summary>
        public List<FieldPlan>? Fields { get; }

        /// <summary>Hand-written writer to call for a Custom operation; <see langword="null" /> for a generated codec body.</summary>
        public string? CustomWriteMethod { get; }

        /// <summary>Hand-written reader to call for a Custom operation; <see langword="null" /> for a generated codec body.</summary>
        public string? CustomReadMethod { get; }

        public static OperationPlan Mechanical(string fullyQualifiedTypeName, string caseLabel, List<FieldPlan> fields)
        {
            return new OperationPlan(fullyQualifiedTypeName, caseLabel, fields, null, null);
        }

        public static OperationPlan Custom(string fullyQualifiedTypeName, string caseLabel, string writeMethod, string readMethod)
        {
            return new OperationPlan(fullyQualifiedTypeName, caseLabel, null, writeMethod, readMethod);
        }
    }

    private sealed class FieldPlan
    {
        public FieldPlan(string parameterName, string writeTemplate, string readExpression)
        {
            ParameterName = parameterName;
            WriteTemplate = writeTemplate;
            ReadExpression = readExpression;
        }

        public string ParameterName { get; }

        public string WriteTemplate { get; }

        public string ReadExpression { get; }
    }
}
