<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\Numos.CoreSim\Version.props"/>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Numos.Collections</PackageId>
        <Title>Numos Collections</Title>
        <Description>Collections and mathematical primitives for 3D chunks and floating point math used by Numos.</Description>
        <PackageTags>simulation;mathematics;collections;voxel;nativeaot</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

</Project>
