using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Numos.Units.Analyzers;

/// <summary>Generates zero-cost global aliases from <c>*.numosunits</c> additional files.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class QuantityAliasGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<AdditionalText> catalogs = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(".numosunits", StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(
            catalogs.Collect(),
            static (productionContext, files) =>
            {
                var catalog = UnitCatalog.Parse(
                    files,
                    productionContext.CancellationToken,
                    productionContext.ReportDiagnostic);

                if (catalog.Definitions.Length == 0)
                    return;

                var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
                foreach (var definition in catalog.Definitions.OrderBy(
                             item => item.Alias,
                             StringComparer.Ordinal))
                    source.Append("global using ").Append(definition.Alias).Append(" = ")
                        .Append(definition.StorageType).AppendLine(";");

                if (catalog.Conversions.Length > 0)
                {
                    source.AppendLine()
                        .AppendLine("namespace Numos.Units.Generated")
                        .AppendLine("{")
                        .AppendLine("    /// <summary>Catalog-generated conversions to and from canonical solver units.</summary>")
                        .AppendLine("    public static class UnitConversions")
                        .AppendLine("    {");

                    foreach (var conversion in catalog.Conversions.OrderBy(item => item.UnitName, StringComparer.Ordinal))
                    {
                        string scale = GetLiteral(conversion.Scale, conversion.StorageType);
                        string offset = GetLiteral(conversion.Offset, conversion.StorageType);
                        source.Append("        [return: global::Numos.Units.QuantityAttribute(\"")
                            .Append(conversion.QuantityId).AppendLine("\")]")
                            .Append("        public static ").Append(conversion.StorageType)
                            .Append(" From").Append(conversion.UnitName).Append('(')
                            .Append(conversion.StorageType).Append(" value) => value * ")
                            .Append(scale).Append(" + ").Append(offset).AppendLine(";")
                            .AppendLine()
                            .Append("        public static ").Append(conversion.StorageType)
                            .Append(" To").Append(conversion.UnitName)
                            .Append("([global::Numos.Units.QuantityAttribute(\"")
                            .Append(conversion.QuantityId).Append("\")] ")
                            .Append(conversion.StorageType).Append(" value) => (value - ")
                            .Append(offset).Append(") / ").Append(scale).AppendLine(";")
                            .AppendLine();
                    }

                    source.AppendLine("    }").AppendLine("}");
                }

                productionContext.AddSource(
                    "Numos.QuantityAliases.g.cs",
                    SourceText.From(source.ToString(), Encoding.UTF8));
            });
    }

    private static string GetLiteral(double value, string storageType)
    {
        string text = value.ToString("R", CultureInfo.InvariantCulture);
        if (!text.Contains('.') && !text.Contains('E') && !text.Contains('e'))
            text += ".0";

        return storageType.EndsWith("Single", StringComparison.Ordinal) ? text + "f" : text + "d";
    }
}